name: Scheduled Tasks

on:
    schedule:
        - cron: "0 6,18 * * *" # Twice a day at 06:00 and 18:00 UTC
    workflow_dispatch: {}

jobs:
    run-scheduled-task:
        runs-on: ubuntu-latest
        steps:
            - name: Print timestamp
              run: echo "Running scheduled maintenance at $(date -u)"
            - name: Ping scheduler endpoint (if configured)
              if: ${{ secrets.MCP_SCHEDULE_URL != '' && secrets.SCHEDULE_TOKEN != '' }}
              env:
                  MCP_SCHEDULE_URL: ${{ secrets.MCP_SCHEDULE_URL }}
                  SCHEDULE_TOKEN: ${{ secrets.SCHEDULE_TOKEN }}
              run: |
                  echo "Pinging $MCP_SCHEDULE_URL"
                  curl -fsS --retry 3 -H "Authorization: Bearer ${SCHEDULE_TOKEN}" "$MCP_SCHEDULE_URL"
